// <autogenerated>
//   This file was generated by T4 code generator ViewModelGenerator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


var crudControllers = angular.module('crudDataControllers', []);


	crudControllers.controller('employeeController', function ($scope, $http) {
    $http.get('../api/Employee').success(function (data) {
        $scope.data = data;
    });
}
);

	
	crudControllers.controller('employerController', function ($scope, $http) {
    $http.get('../api/Employer').success(function (data) {
        $scope.data = data;
    });
}
);

	
	crudControllers.controller('salarycalculationController', function ($scope, $http) {
    $http.get('../api/SalaryCalculation').success(function (data) {
        $scope.data = data;
    });
}
);

	
	crudControllers.controller('taxcardController', function ($scope, $http) {
    $http.get('../api/Taxcard').success(function (data) {
        $scope.data = data;
    });
}
);

	