//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mikkark.SCA.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculationRow
    {
        public string Id { get; set; }
        public string Value { get; set; }
        public string TypeId { get; set; }
    
        public virtual CalculationRowType CalculationRowType { get; set; }
    }
}
